// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniCatalog.Data.Data;

#nullable disable

namespace UniCatalog.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240627120632_Profesori")]
    partial class Profesori
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UniCatalog.Models.CadruDidactic", b =>
                {
                    b.Property<string>("MarcaAngajat")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DisciplinaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Post")
                        .HasColumnType("int");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titlu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaAngajat");

                    b.ToTable("CadreDidactice");

                    b.HasData(
                        new
                        {
                            MarcaAngajat = "13ef1",
                            DisciplinaId = "15ab1",
                            Nume = "Popescu",
                            Post = 0,
                            Prenume = "Ion",
                            Titlu = "Dr."
                        },
                        new
                        {
                            MarcaAngajat = "13ef2",
                            DisciplinaId = "15ab2",
                            Nume = "Georgescu",
                            Post = 3,
                            Prenume = "Marius",
                            Titlu = "Dr. Ing."
                        },
                        new
                        {
                            MarcaAngajat = "13ef3",
                            DisciplinaId = "15ab3",
                            Nume = "Ion",
                            Post = 3,
                            Prenume = "Elena",
                            Titlu = "Dr."
                        },
                        new
                        {
                            MarcaAngajat = "13ef4",
                            DisciplinaId = "15ab4",
                            Nume = "Radu",
                            Post = 0,
                            Prenume = "Constantin",
                            Titlu = "Dr."
                        },
                        new
                        {
                            MarcaAngajat = "13ef5",
                            DisciplinaId = "15ab5",
                            Nume = "Pop",
                            Post = 4,
                            Prenume = "Carmen",
                            Titlu = "Dr.Ing."
                        },
                        new
                        {
                            MarcaAngajat = "13ef6",
                            DisciplinaId = "15ab6",
                            Nume = "Dan",
                            Post = 2,
                            Prenume = "Alexandra",
                            Titlu = "Dr."
                        },
                        new
                        {
                            MarcaAngajat = "13ef7",
                            DisciplinaId = "15ab7",
                            Nume = "Ionescu",
                            Post = 3,
                            Prenume = "Maria",
                            Titlu = "Dr."
                        });
                });

            modelBuilder.Entity("UniCatalog.Models.Disciplina", b =>
                {
                    b.Property<string>("Cod")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Acronim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Credite")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.HasKey("Cod");

                    b.ToTable("Discipline");

                    b.HasData(
                        new
                        {
                            Cod = "15ab1",
                            Acronim = "TS",
                            Credite = 4,
                            Name = "Teoria Sistemelor",
                            PlanId = 2
                        },
                        new
                        {
                            Cod = "15ab2",
                            Acronim = "F",
                            Credite = 5,
                            Name = "Fizica",
                            PlanId = 2
                        },
                        new
                        {
                            Cod = "15ab3",
                            Acronim = "MS",
                            Credite = 6,
                            Name = "Matematici Speciale",
                            PlanId = 2
                        },
                        new
                        {
                            Cod = "15ab4",
                            Acronim = "E",
                            Credite = 3,
                            Name = "Electrotehnica",
                            PlanId = 2
                        },
                        new
                        {
                            Cod = "15ab5",
                            Acronim = "ALGAD",
                            Credite = 6,
                            Name = "Algebra Liniara",
                            PlanId = 1
                        },
                        new
                        {
                            Cod = "15ab6",
                            Acronim = "PCLP",
                            Credite = 5,
                            Name = "Programarea Calclatoarelor",
                            PlanId = 1
                        },
                        new
                        {
                            Cod = "15ab7",
                            Acronim = "POO",
                            Credite = 4,
                            Name = "Programare orientata pe obiect",
                            PlanId = 1
                        });
                });

            modelBuilder.Entity("UniCatalog.Models.Grupa", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Grupa");
                });

            modelBuilder.Entity("UniCatalog.Models.PlanDeInvatamant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("An")
                        .HasColumnType("int");

                    b.Property<int>("CicluDeInvatamant")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PlanuriDeInvatamant");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            An = 1,
                            CicluDeInvatamant = 0,
                            Name = "AIA"
                        },
                        new
                        {
                            Id = 2,
                            An = 2,
                            CicluDeInvatamant = 1,
                            Name = "AIA"
                        });
                });

            modelBuilder.Entity("UniCatalog.Models.Student", b =>
                {
                    b.Property<string>("NrMatricol")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("DataInscrierii")
                        .HasColumnType("datetime2");

                    b.Property<string>("GrupaName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("MedieAdmitere")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlanDeInvatamantId")
                        .HasColumnType("int");

                    b.Property<int?>("PlanId")
                        .HasColumnType("int");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NrMatricol");

                    b.HasIndex("GrupaName");

                    b.HasIndex("PlanDeInvatamantId");

                    b.ToTable("Student");

                    b.HasData(
                        new
                        {
                            NrMatricol = "10917/4lf422019",
                            CNP = "5030610211245",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3878),
                            MedieAdmitere = 7.5,
                            Name = "Snow",
                            PlanId = 1,
                            Prenume = "Jon"
                        },
                        new
                        {
                            NrMatricol = "10918/4lf422019",
                            CNP = "5040710211234",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3937),
                            MedieAdmitere = 8.0999999999999996,
                            Name = "Stark",
                            PlanId = 1,
                            Prenume = "Arya"
                        },
                        new
                        {
                            NrMatricol = "10919/4lf422019",
                            CNP = "5030810211256",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3940),
                            MedieAdmitere = 8.6999999999999993,
                            Name = "Lannister",
                            PlanId = 1,
                            Prenume = "Tyrion"
                        },
                        new
                        {
                            NrMatricol = "10920/4lf422019",
                            CNP = "5030910211267",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3942),
                            MedieAdmitere = 9.0,
                            Name = "Targaryen",
                            PlanId = 2,
                            Prenume = "Daenerys"
                        },
                        new
                        {
                            NrMatricol = "10921/4lf422019",
                            CNP = "5031010211278",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3944),
                            MedieAdmitere = 7.7999999999999998,
                            Name = "Baratheon",
                            PlanId = 2,
                            Prenume = "Robert"
                        },
                        new
                        {
                            NrMatricol = "10922/4lf422019",
                            CNP = "5031110211289",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3946),
                            MedieAdmitere = 7.2999999999999998,
                            Name = "Greyjoy",
                            PlanId = 1,
                            Prenume = "Theon"
                        },
                        new
                        {
                            NrMatricol = "10923/4lf422019",
                            CNP = "5031210211290",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3950),
                            MedieAdmitere = 8.5,
                            Name = "Mormont",
                            PlanId = 2,
                            Prenume = "Jorah"
                        },
                        new
                        {
                            NrMatricol = "10924/4lf422019",
                            CNP = "5031310211301",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3952),
                            MedieAdmitere = 8.9000000000000004,
                            Name = "Tyrell",
                            PlanId = 2,
                            Prenume = "Margaery"
                        },
                        new
                        {
                            NrMatricol = "10925/4lf422019",
                            CNP = "5031410211312",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3954),
                            MedieAdmitere = 8.1999999999999993,
                            Name = "Sand",
                            PlanId = 1,
                            Prenume = "Oberyn"
                        },
                        new
                        {
                            NrMatricol = "10926/4lf422019",
                            CNP = "5031510211323",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3956),
                            MedieAdmitere = 8.3000000000000007,
                            Name = "Martell",
                            PlanId = 2,
                            Prenume = "Ellaria"
                        },
                        new
                        {
                            NrMatricol = "10927/4lf422019",
                            CNP = "5031610211334",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3959),
                            MedieAdmitere = 7.9000000000000004,
                            Name = "Tarly",
                            PlanId = 1,
                            Prenume = "Samwell"
                        },
                        new
                        {
                            NrMatricol = "10928/4lf422019",
                            CNP = "5031710211345",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3961),
                            MedieAdmitere = 7.2000000000000002,
                            Name = "Bolton",
                            PlanId = 2,
                            Prenume = "Ramsay"
                        },
                        new
                        {
                            NrMatricol = "10929/4lf422019",
                            CNP = "5031810211356",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3964),
                            MedieAdmitere = 8.4000000000000004,
                            Name = "Baelish",
                            PlanId = 1,
                            Prenume = "Petyr"
                        },
                        new
                        {
                            NrMatricol = "10930/4lf422019",
                            CNP = "5031910211367",
                            DataInscrierii = new DateTime(2024, 6, 27, 15, 6, 31, 925, DateTimeKind.Local).AddTicks(3966),
                            MedieAdmitere = 8.0,
                            Name = "Clegane",
                            PlanId = 2,
                            Prenume = "Sandor"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UniCatalog.Models.Student", b =>
                {
                    b.HasOne("UniCatalog.Models.Grupa", "Grupa")
                        .WithMany("Student")
                        .HasForeignKey("GrupaName");

                    b.HasOne("UniCatalog.Models.PlanDeInvatamant", "PlanDeInvatamant")
                        .WithMany()
                        .HasForeignKey("PlanDeInvatamantId");

                    b.Navigation("Grupa");

                    b.Navigation("PlanDeInvatamant");
                });

            modelBuilder.Entity("UniCatalog.Models.Grupa", b =>
                {
                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
